db:
  user: "your_mysql_username"
  pw: "your_mysql_password"
  host: "mysql.clarksonsmsda.org"
  db: "ia637_LibraryManagementSystem"

tables:
  Users: Users
  Titles: Titles
  Books: Books
  Loans: Loans

